version: '3.7'

configs:
  authorized_keys:
    file: 'authorized_keys'

services:

  redis:
    restart: 'unless-stopped'
    image: 'redis:3.2-alpine'
    command: 'redis-server'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  db:
    restart: 'unless-stopped'
    image: 'mysql/mysql-server:5.7'
    env_file: '.env'
    volumes:
      - 'db:/var/lib/mysql'
  phalt_app:
    image: 'phalt:latest'
    ports:
      - '9292'
    env_file: '.env_phalt'
  web:
    restart: 'unless-stopped'
    depends_on:
      - 'db'
      - 'redis'
    configs:
      - source: 'authorized_keys'
        target: '/home/gitannex/.ssh/authorized_keys'
    image: 'colenda_web:latest'
    ports:
      - '80:80'
      - '${SSH_PORT}:22'
    env_file:
      - '.env'
    networks:
      default:
        aliases:
          - 'web'
    volumes:
      - 'web:/home/app/webapp'
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - '${OPENN_HARVESTING_ENDPOINT_LOCAL}:${OPENN_HARVESTING_ENDPOINT_REMOTE}'
      - '${KAPLAN_HARVESTING_ENDPOINT_LOCAL}:${KAPLAN_HARVESTING_ENDPOINT_REMOTE}'
      - '${PAP_HARVESTING_ENDPOINT_LOCAL}:${PAP_HARVESTING_ENDPOINT_REMOTE}'
      - '${LOCAL_WORKSPACE}:${REMOTE_WORKSPACE}'
      - '${LOCAL_FEATURED}:/home/app/webapp/public/assets/featured'
  sidekiq:
    restart: 'unless-stopped'
    depends_on:
      - 'redis'
    image: 'colenda_web:latest'
    ports:
      - '25:25'
    env_file:
      - '.env'
    command: 'bundle exec sidekiq -C config/sidekiq.yml'
    volumes:
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - '${OPENN_HARVESTING_ENDPOINT_LOCAL}:${OPENN_HARVESTING_ENDPOINT_REMOTE}'
      - '${KAPLAN_HARVESTING_ENDPOINT_LOCAL}:${KAPLAN_HARVESTING_ENDPOINT_REMOTE}'
      - '${LOCAL_WORKSPACE}:${REMOTE_WORKSPACE}'
  rabbitmq:
    restart: 'unless-stopped'
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    ports:
      - '15672:15672'

volumes:
  redis:
  db:
  web:

