version: '3.7'

configs:
  authorized_keys:
    file: authorized_keys

secrets:
  bulwark_database_password:
    external: true
    name: colenda_bulwark_database_password
  bulwark_database_root_password:
    external: true
    name: colenda_bulwark_database_root_password
  bulwark_database_config:
    external: true
    name: colenda_bulwark_database_config
  bulwark_secrets_config:
    external: true
    name: colenda_bulwark_secrets_config
  bulwark_ssh_host_dsa_key:
    external: true
    name: colenda_bulwark_ssh_host_dsa_key
  bulwark_ssh_host_ecdsa_key:
    external: true
    name: colenda_bulwark_ssh_host_ecdsa_key
  bulwark_ssh_host_ed25519_key:
    external: true
    name: colenda_bulwark_ssh_host_ed25519_key
  bulwark_ssh_host_rsa_key:
    external: true
    name: colenda_bulwark_ssh_host_rsa_key

services:
  redis:
    image: 'redis:3.2-alpine'
    command: 'redis-server'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  db:
    image: 'mysql:5.7'
    deploy:
      endpoint_mode: dnsrr
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD_FILE: /run/secrets/bulwark_database_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/bulwark_database_root_password
      MYSQL_USER: ${DATABASE_USERNAME}
    secrets:
      - bulwark_database_password
      - bulwark_database_root_password
    volumes:
      - 'db:/var/lib/mysql'
  phalt_app:
    image: 'phalt:latest'
    environment:
      IIIF:
      IIIF_BASE:
      OAI_PMH:
      VIRTUAL_HOST:
      VIRTUAL_URL:
      DOWNLOAD_LINK:
      DOWNLOAD_PORT:
      MARMITE_BASE:
      MARMITE_FORMAT:
    ports:
      - '9292'
  web:
    image: 'quay.io/upennlibraries/bulwark:${BULWARK_IMAGE_TAG}'
    configs:
      - source: 'authorized_keys'
        target: '/home/gitannex/.ssh/authorized_keys'
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      BATCH_OPS_EMAIL:
      CACHE_URL:
      CATALOG_CONTROLLER_PROTOCOL:
      COMBINED_HTTP_LOOKUP:
      DATABASE_NAME:
      DATABASE_USERNAME:
      ERC_DEFAULT_WHO:
      EZID_DEFAULT_SHOULDER:
      EZID_PASSWORD:
      EZID_USER:
      GIT_USER:
      GIT_USER_PASS:
      IIIF_IMAGE_SERVER:
      IMAGING_USER:
      IMAGING_USER_PASS:
      KAPLAN_HARVESTING_ENDPOINT_REMOTE:
      KAPLAN_INITIAL_STOP:
      KAPLAN_OWNER:
      KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE:
      MATOMO_EMBED:
      OPENN_DESCRIPTION:
      OPENN_HARVESTING_ENDPOINT_REMOTE:
      OPENN_INITIAL_STOP:
      OPENN_OWNER:
      PAP_DESCRIPTION:
      PAP_HARVESTING_ENDPOINT_REMOTE:
      PAP_HTTP_LOOKUP:
      PAP_STRUCTURAL_HTTP_LOOKUP:
      PAP_INITIAL_STOP:
      PAP_OWNER:
      PHALT_ENDPOINT:
      PROD_FEDORA_PW:
      PROD_FEDORA_URL:
      PROD_FEDORA_USER:
      PROD_SOLR_URL:
      PUBLIC_FEDORA_URL:
      RAILS_ENV:
      REDIS_URL:
      REQUEST_STYLE:
      SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE:
      SMTP_ADDRESS:
      SMTP_DOMAIN:
      SMTP_PORT:
      SPECIAL_REMOTE_NAME:
      STORAGE_ENCRYPTION:
      STORAGE_HOST:
      STORAGE_PORT:
      STORAGE_PROTOCOL:
      STORAGE_PUBLIC:
      STORAGE_READ_HOST:
      STORAGE_READ_PROTOCOL:
      STORAGE_TYPE:
      UV_URL:
      VOYAGER_HTTP_LOOKUP:
      VOYAGER_STRUCTURAL_HTTP_LOOKUP:
    networks:
      default:
        aliases:
          - 'web'
    ports:
      - '80:80'
      - '${SSH_PORT}:22'
    secrets:
      - source: bulwark_database_config
        target: /home/app/webapp/config/database.yml
      - source: bulwark_secrets_config
        target: /home/app/webapp/config/secrets.yml
      - source: bulwark_ssh_host_dsa_key
        target: /etc/ssh/ssh_host_dsa_key
        mode: 0400
      - source: bulwark_ssh_host_ecdsa_key
        target: /etc/ssh/ssh_host_ecdsa_key
        mode: 0400
      - source: bulwark_ssh_host_ed25519_key
        target: /etc/ssh/ssh_host_ed25519_key
        mode: 0400
      - source: bulwark_ssh_host_rsa_key
        target: /etc/ssh/ssh_host_rsa_key
        mode: 0400
    volumes:
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - '${OPENN_HARVESTING_ENDPOINT_LOCAL}:${OPENN_HARVESTING_ENDPOINT_REMOTE}'
      - '${KAPLAN_HARVESTING_ENDPOINT_LOCAL}:${KAPLAN_HARVESTING_ENDPOINT_REMOTE}'
      - '${PAP_HARVESTING_ENDPOINT_LOCAL}:${PAP_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_2:${SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_3:${SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE}'
      - 'scanstore_rescue:${SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'kaplan_rescue:${KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'colenda_workspace:${REMOTE_WORKSPACE}'
      - '${LOCAL_FEATURED}:/home/app/webapp/public/assets/featured'
  sidekiq:
    image: 'quay.io/upennlibraries/bulwark:${BULWARK_IMAGE_TAG}'
    command: bash -c "/etc/my_init.d/gitannex.sh && /etc/my_init.d/imaging.sh && /sbin/my_init --skip-startup-files --skip-runit -- bundle exec sidekiq -C config/sidekiq.yml"
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      BATCH_OPS_EMAIL:
      CACHE_URL:
      CATALOG_CONTROLLER_PROTOCOL:
      DATABASE_NAME:
      DATABASE_USERNAME:
      ERC_DEFAULT_WHO:
      EZID_DEFAULT_SHOULDER:
      EZID_PASSWORD:
      EZID_USER:
      GIT_USER:
      GIT_USER_PASS:
      IIIF_IMAGE_SERVER:
      IMAGING_USER:
      IMAGING_USER_PASS:
      KAPLAN_HARVESTING_ENDPOINT_REMOTE:
      KAPLAN_INITIAL_STOP:
      KAPLAN_OWNER:
      OPENN_DESCRIPTION:
      OPENN_HARVESTING_ENDPOINT_REMOTE:
      OPENN_INITIAL_STOP:
      OPENN_OWNER:
      PAP_DESCRIPTION:
      PAP_HARVESTING_ENDPOINT_REMOTE:
      PAP_HTTP_LOOKUP:
      PAP_STRUCTURAL_HTTP_LOOKUP:
      PAP_INITIAL_STOP:
      PAP_OWNER:
      PHALT_ENDPOINT:
      PROD_FEDORA_PW:
      PROD_FEDORA_URL:
      PROD_FEDORA_USER:
      PROD_SOLR_URL:
      PUBLIC_FEDORA_URL:
      RAILS_ENV:
      REDIS_URL:
      REQUEST_STYLE:
      SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE:
      SMTP_ADDRESS:
      SMTP_DOMAIN:
      SMTP_PORT:
      SPECIAL_REMOTE_NAME:
      STORAGE_ENCRYPTION:
      STORAGE_HOST:
      STORAGE_PORT:
      STORAGE_PROTOCOL:
      STORAGE_PUBLIC:
      STORAGE_READ_HOST:
      STORAGE_READ_PROTOCOL:
      STORAGE_TYPE:
      VOYAGER_HTTP_LOOKUP:
      VOYAGER_STRUCTURAL_HTTP_LOOKUP:
    ports:
      - '25:25'
    secrets:
      - source: bulwark_database_config
        target: /home/app/webapp/config/database.yml
      - source: bulwark_secrets_config
        target: /home/app/webapp/config/secrets.yml
    volumes:
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - '${OPENN_HARVESTING_ENDPOINT_LOCAL}:${OPENN_HARVESTING_ENDPOINT_REMOTE}'
      - '${KAPLAN_HARVESTING_ENDPOINT_LOCAL}:${KAPLAN_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_2:${SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_3:${SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE}'
      - 'scanstore_rescue:${SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'kaplan_rescue:${KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'colenda_workspace:${REMOTE_WORKSPACE}'
  sidekiq_xml:
    image: 'quay.io/upennlibraries/bulwark:${BULWARK_IMAGE_TAG}'
    command: bash -c "/etc/my_init.d/gitannex.sh && /etc/my_init.d/imaging.sh && /sbin/my_init --skip-startup-files --skip-runit -- bundle exec sidekiq -C config/sidekiq_xml.yml"
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      BATCH_OPS_EMAIL:
      CACHE_URL:
      CATALOG_CONTROLLER_PROTOCOL:
      DATABASE_NAME:
      DATABASE_USERNAME:
      ERC_DEFAULT_WHO:
      EZID_DEFAULT_SHOULDER:
      EZID_PASSWORD:
      EZID_USER:
      GIT_USER:
      GIT_USER_PASS:
      IIIF_IMAGE_SERVER:
      IMAGING_USER:
      IMAGING_USER_PASS:
      KAPLAN_HARVESTING_ENDPOINT_REMOTE:
      KAPLAN_INITIAL_STOP:
      KAPLAN_OWNER:
      OPENN_DESCRIPTION:
      OPENN_HARVESTING_ENDPOINT_REMOTE:
      OPENN_INITIAL_STOP:
      OPENN_OWNER:
      PAP_DESCRIPTION:
      PAP_HARVESTING_ENDPOINT_REMOTE:
      PAP_HTTP_LOOKUP:
      PAP_STRUCTURAL_HTTP_LOOKUP:
      PAP_INITIAL_STOP:
      PAP_OWNER:
      PHALT_ENDPOINT:
      PROD_FEDORA_PW:
      PROD_FEDORA_URL:
      PROD_FEDORA_USER:
      PROD_SOLR_URL:
      PUBLIC_FEDORA_URL:
      RAILS_ENV:
      REDIS_URL:
      REQUEST_STYLE:
      SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE:
      SMTP_ADDRESS:
      SMTP_DOMAIN:
      SMTP_PORT:
      SPECIAL_REMOTE_NAME:
      STORAGE_ENCRYPTION:
      STORAGE_HOST:
      STORAGE_PORT:
      STORAGE_PROTOCOL:
      STORAGE_PUBLIC:
      STORAGE_READ_HOST:
      STORAGE_READ_PROTOCOL:
      STORAGE_TYPE:
      VOYAGER_HTTP_LOOKUP:
      VOYAGER_STRUCTURAL_HTTP_LOOKUP:
    ports:
      - '26:25'
    secrets:
      - source: bulwark_database_config
        target: /home/app/webapp/config/database.yml
      - source: bulwark_secrets_config
        target: /home/app/webapp/config/secrets.yml
    volumes:
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - '${OPENN_HARVESTING_ENDPOINT_LOCAL}:${OPENN_HARVESTING_ENDPOINT_REMOTE}'
      - '${KAPLAN_HARVESTING_ENDPOINT_LOCAL}:${KAPLAN_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_2:${SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_3:${SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE}'
      - 'scanstore_rescue:${SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'kaplan_rescue:${KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'colenda_workspace:${REMOTE_WORKSPACE}'
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    ports:
      - '15672:15672'
  sidekiq_metadata:
    image: 'quay.io/upennlibraries/bulwark:${BULWARK_IMAGE_TAG}'
    command: bash -c "/etc/my_init.d/gitannex.sh && /etc/my_init.d/imaging.sh && /sbin/my_init --skip-startup-files --skip-runit -- bundle exec sidekiq -C config/sidekiq_metadata.yml"
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      BATCH_OPS_EMAIL:
      CACHE_URL:
      CATALOG_CONTROLLER_PROTOCOL:
      DATABASE_NAME:
      DATABASE_USERNAME:
      ERC_DEFAULT_WHO:
      EZID_DEFAULT_SHOULDER:
      EZID_PASSWORD:
      EZID_USER:
      GIT_USER:
      GIT_USER_PASS:
      IIIF_IMAGE_SERVER:
      IMAGING_USER:
      IMAGING_USER_PASS:
      KAPLAN_HARVESTING_ENDPOINT_REMOTE:
      KAPLAN_INITIAL_STOP:
      KAPLAN_OWNER:
      OPENN_DESCRIPTION:
      OPENN_HARVESTING_ENDPOINT_REMOTE:
      OPENN_INITIAL_STOP:
      OPENN_OWNER:
      PAP_DESCRIPTION:
      PAP_HARVESTING_ENDPOINT_REMOTE:
      PAP_HTTP_LOOKUP:
      PAP_STRUCTURAL_HTTP_LOOKUP:
      PAP_INITIAL_STOP:
      PAP_OWNER:
      PHALT_ENDPOINT:
      PROD_FEDORA_PW:
      PROD_FEDORA_URL:
      PROD_FEDORA_USER:
      PROD_SOLR_URL:
      PUBLIC_FEDORA_URL:
      RAILS_ENV:
      REDIS_URL:
      REQUEST_STYLE:
      SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE:
      SMTP_ADDRESS:
      SMTP_DOMAIN:
      SMTP_PORT:
      SPECIAL_REMOTE_NAME:
      STORAGE_ENCRYPTION:
      STORAGE_HOST:
      STORAGE_PORT:
      STORAGE_PROTOCOL:
      STORAGE_PUBLIC:
      STORAGE_READ_HOST:
      STORAGE_READ_PROTOCOL:
      STORAGE_TYPE:
      VOYAGER_HTTP_LOOKUP:
      VOYAGER_STRUCTURAL_HTTP_LOOKUP:
    ports:
      - '27:25'
    secrets:
      - source: bulwark_database_config
        target: /home/app/webapp/config/database.yml
      - source: bulwark_secrets_config
        target: /home/app/webapp/config/secrets.yml
    volumes:
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - '${OPENN_HARVESTING_ENDPOINT_LOCAL}:${OPENN_HARVESTING_ENDPOINT_REMOTE}'
      - '${KAPLAN_HARVESTING_ENDPOINT_LOCAL}:${KAPLAN_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_2:${SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_3:${SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE}'
      - 'scanstore_rescue:${SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'kaplan_rescue:${KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'colenda_workspace:${REMOTE_WORKSPACE}'
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    ports:
      - '15672:15672'

volumes:
  colenda_workspace:
    external: true
  sceti_completed_2:
    external: true
  sceti_completed_3:
    external: true
  scanstore_rescue:
    external: true
  kaplan_rescue:
    external: true
  redis:
  db:
